
name: Build Package And publish on PyPi

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build_distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: |
        cd analyzer
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        # pip install build
        # python -m build --wheel
        python setup.py sdist bdist_wheel
        ls -la 
        ls -la dist/
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4.2.0
      with:
        name: python-package-distributions
        path: analyzer/dist/

  release-on-pypi:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testpypi
      url: https://test.pypi.org/p/daxa
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4.1.1
        with:
          name: python-package-distributions
          path: analyzer/dist/

      - name: Build and Upload to Test PyPI
        run: |
          python -m pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ analyzer/dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        
      # - name: Publish Daxa Distribution to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
      #     packages-dir: analyzer/dist/
