
name: Build Package And publish on Test PyPi

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build_distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.x"
    - name: Install pypa/build
      run: |
        pip install build
        python -m build --wheel
        ls -la 
        ls -la dist/
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4.2.0
      with:
        name: pebblo-package-distributions
        path: dist/

  release-on-test-pypi:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testpypi
      url: https://test.pypi.org/p/daxa
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4.1.1
        with:
          name: pebblo-package-distributions
          path: dist/

      - name: Upload to Test PyPI
        run: |
          pip install twine
          twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        
