name: Docker image release

on:
  push:
    branches:
      - docker-pebble-file
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"
jobs:
  build-and-push:
    name: Build base image
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Get Release Tag
        run: |
          #TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          #echo "VERSION=$(echo $TAG | sed 's/v//')" >> $GITHUB_ENV
          echo "VERSION=$(echo "v0.1.13")" >> $GITHUB_ENV
          whoami
         
      - name: Build base images
        uses: docker/bake-action@v4
        env:
          IMAGE_TAG_SUFFIX: ${{ env.VERSION }}
          PEBBLO_VERSION: ${{ env.VERSION }}
        with:
          workdir: docker
          targets: base
          push: true
     
